name: Build
on:
  push:
    branches:
      - main
      - feature/initial
  workflow_dispatch:
    inputs:
      image_version:
        description: "Image tag version"
        required: true
        default: latest

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ghcr.io/david-lor/archiveorg-telegrambot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Verify if any of the image-involved files changed
        id: changed-files
        uses: tj-actions/changed-files@v11.5
        with:
          files: |
            .dockerignore
            Dockerfile
            src/**
            .github/workflows/build-push.yaml
      - name: Set flag for triggering test & build jobs
        if: ${{ steps.changed-files.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch' }}
        run: echo "build=true" >> $GITHUB_ENV

      - name: Set image tag + version (latest)
        if: ${{ env.build == 'true' && github.event_name != 'workflow_dispatch' }}
        run: |
          echo "${{ env.IMAGE_TAG }}:latest" >> $GITHUB_ENV
      - name: Set image tag + version (workflow_dispatch)
        if: ${{ env.build == 'true' && github.event_name == 'workflow_dispatch' }}
        run: |
          echo "${{ env.IMAGE_TAG }}:${{ github.event.inputs.image_version }}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        if: ${{ env.build == 'true' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Build
        if: ${{ env.build == 'true' }}
        run: docker build . -t ${{ env.IMAGE_TAG }}
      - name: Docker Push
        if: ${{ env.build == 'true' }}
        run: docker push ${{ env.IMAGE_TAG }}
